### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#10]
As a guest I want to sign up to become a user so that I can save my information for booking or receiving news from system

**Acceptance test**
- [x] Requirement fields for sign up: gender, full name, email
- [x] Optional field for sign up: phone number
- [x] Email requires unique
- [x] Gender, full name, phone number doesn't require unique
- [x] Phone number has to be correct format (if user input)

Optional
- [ ] User can choose avatar in 2 ways: list avatar suggestion from system OR upload his/her avatar
- [ ] User can login as facebook account
- [ ] User can receive email after sign up

**Comment by hongtran** [comment]
-  Create form, controller for sign-up

**Comment by hongtran** [comment]
Completed this issue, pls review for me.
