### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#28]
As a Vietnamese user I want website support Vietnamese language so that I can use website easier
**Acceptant test**
- [ ] Support Vietnamese & English
- [ ] Default language is English
- [ ] User can switch to Vietnamese easily from home page

**Comment by hongtran** [comment]
Sample how to implement multi language in our app.
1. In config/locales/en.yml file 
![languagefile](https://cloud.githubusercontent.com/assets/8022525/18112650/64449de6-6f53-11e6-9de8-bc396f59500a.png)
2. In template app/views/homes/index.html.erb
![template](https://cloud.githubusercontent.com/assets/8022525/18112678/9b1be248-6f53-11e6-8559-1bb0c72296d9.png)
