### ISSUE TITLE
Git collaboration guide

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#3]
As a dev team, I want a git collaboration guide so that I can easier to look up when I use github
Acceptance test
- [x] Flow process description: https://github.com/middle-guys/iflight/wiki/Workflow
- [x] Cheat-sheet common github commands: https://github.com/middle-guys/iflight/wiki/Github-Commands

**Comment by tangten** [comment]
I often use SourceTree to push or pull source code and I don't know a lot of Github commands. So I searched and found a Github commands file. Hope to useful for us :)

**Comment by leo-le-07** [comment]
Great. Can we move that guides to wiki page ? This story will be go to `Done` or `Close`

**Comment by tangten** [comment]
done 💯
