### ISSUE TITLE
#22 GIF Workflow for Sign up, Sign in features

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#42]
#22

**Acceptance test**
- [ ] Write down some summary about features for your GIF workflow

**Comment by hongtran** [comment]
![walkthrough](http://i.imgur.com/sAvWMD8.gif)

**Comment by hongtran** [comment]
We use **devise** gem for sign-up, sign-in user, remember password user...

**Comment by leo-le-07** [comment]
Great ! Thanks Hong
