### ISSUE TITLE
#22 GIF Workflow for crawl data from 3 airline websites

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#43]
#22

**Acceptance test**
- [x] Write down some summary about features for your GIF workflow

**Comment by tangnv** [comment]
![walkthrough](https://cloud.githubusercontent.com/assets/4475472/17615419/6422e8aa-6098-11e6-9ec9-b42f67f58104.gif)

**Comment by tangten** [comment]
![walkthrough](https://cloud.githubusercontent.com/assets/4475472/17616319/21230aca-609e-11e6-900a-d0287a986722.gif)

**Comment by tangten** [comment]
Run test in `rails console`:
- One Way:

```
SearchFlight::Base.new(ori_code: "SGN", des_code: "HAN", depart_date: Date.today + 1, adult: 1, child: 0, infant: 0, return_date: Date.today + 2, round_type: "OW")
```
- Round Trip:

```
SearchFlight::Base.new(ori_code: "SGN", des_code: "HAN", depart_date: Date.today + 1, adult: 1, child: 0, infant: 0, return_date: nil, round_type: "RT")
```
