### ISSUE TITLE
Review user stories and wireframes

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#8]
Dear @coderschoolreview, our team have already done 
- [x] [User stories (required and optional)](https://github.com/middle-guys/iflight/blob/master/README.md)
- [x] [Prototype main screens](https://github.com/middle-guys/iflight/blob/master/README.md)
- [x] Survey [questions](https://docs.google.com/forms/d/1ZUnMGSLb4FsSD277wMp2JGfskrFDZpXaawkjS9igPUg/viewform?edit_requested=true) and [result](https://github.com/middle-guys/iflight/issues/5#issuecomment-237999553)

**Comment by hongtran** [comment]
Our stories and wireframes are ready for review.
/cc @coderschoolreview
