### ISSUE TITLE
Testing on production

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#85]
**Acceptance test**
## User
- [ ] Sign up
- [ ] Sign in
- [ ] Login
- [ ] Login with remember option
- [ ] Recover password
- [ ] Sign out
- [ ] User's orders page
## Searching
- [ ] Searching flights
- [ ] Top recently searching
- [ ] Top trending searching
- [ ] Click one of top recently searching -> searching flights
- [ ] Sharing cheap ticket to friend's email
## Booking
- [ ] Sorting flight by price, time in flights result page
- [ ] Validate contact & passenger information: email, phone number, name (not date of birth for infant)
- [ ] Sending email after booking success
- [ ] Sending sms after booking success
## Alert
- [ ] Save alert request from user to database
- [ ] Sending email alert confirmation
- [ ] Sending email alert notification when price meet user's price expectation
- [ ] User can unsubscribe alert notification from email

**Comment by hongtran** [comment]
- [x] The change password layout page still old template now -> **adapted**

**Comment by tangten** [comment]
Booking
Data Test: 1 Adult, 1 Child, 1 Infant
- One Way: pass
- Round Trip: pass
- Round Trip Mixing: pass
